version: '3.9'
services:
  app:
    build: .
    image: social-service
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - BIND_IP=0.0.0.0
      - PORT=8080
      - PSQL_USERNAME=postgres
      - PSQL_PASSWORD=admin
      - PSQL_HOST=db
      - PSQL_PORT=5432
      - PSQL_DB=social

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=social
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata: